version: "3.9"

services:
  web-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
